### ISSUE TITLE
Individual chat view

### ISSUE THREAD

**Issue by dipanmht33** [pvphit/Comp-313-Section001-Group-2#1]
A user can search the person using the search button option where he can search the person who, he wants to chat with.
Creating proper user interface for the chat functionality where a user can see the incoming message.
The incoming and outgoing messages will have different color.

**Comment by haocencol** [comment]
This is too general of an issue.  Create stories based on a specific functionalities of the chat feature (e.g., individual chat, group, sending a chat message, cancelling a chat message).

**Comment by haocencol** [comment]
Is this an epic with the above stories?  If yes, create appropriate issues and label as "epic", "user story", and "tasks" to better separate units of work.
