### ISSUE TITLE
Add Security feature for password recovery by email

### ISSUE THREAD

**Issue by pvphit** [pvphit/Comp-313-Section001-Group-2#3]
This feature will allow the user to recover the password via email in case they forget the password.
The recovery password link will be sent to the registered email when the user clicks on the forget password option.
Thereafter the user need to click on the link where the user will be redirected to the page where they can set the password.

**Comment by vagha** [comment]
A user wants to recover their password, well they can't. Their password will be encrypted so that even we don't know what the password is. So instead of recovering their password, we will allow the users to reset their password. Now, for the verification part.we will do the following checks:
Is the email valid?
Is the email-token binding valid?
Is the token expired?
Has the token been used?

If all checks out, we will allow the user to get a new password/verify their email.

**Comment by pvphit** [comment]
![4](https://user-images.githubusercontent.com/46803871/53933162-0d47d300-406b-11e9-93b8-601861a03704.jpg)
![5](https://user-images.githubusercontent.com/46803871/53933163-0d47d300-406b-11e9-88c0-907deb6cfa12.jpg)
![6](https://user-images.githubusercontent.com/46803871/53933164-0d47d300-406b-11e9-8ef1-3d342526317c.jpg)
![1](https://user-images.githubusercontent.com/46803871/53933165-0de06980-406b-11e9-8c94-b73d7810b015.png)
![2](https://user-images.githubusercontent.com/46803871/53933166-0de06980-406b-11e9-8ad1-0f49f7b40925.jpg)
![3](https://user-images.githubusercontent.com/46803871/53933168-0de06980-406b-11e9-9849-e432bc29d8b3.jpg)


Email Recovery Done!

**Comment by pvphit** [comment]
![1](https://user-images.githubusercontent.com/46803871/53933220-42ecbc00-406b-11e9-90e8-1950993116d9.png)

**Comment by pvphit** [comment]
![2](https://user-images.githubusercontent.com/46803871/53933234-5435c880-406b-11e9-9c2a-8af3437c87c9.jpg)

**Comment by pvphit** [comment]
![3](https://user-images.githubusercontent.com/46803871/53933240-5bf56d00-406b-11e9-83b9-5612cc1f2da6.jpg)

**Comment by pvphit** [comment]
![4](https://user-images.githubusercontent.com/46803871/53933246-644da800-406b-11e9-9903-73d34e80d61e.jpg)

**Comment by pvphit** [comment]
![5](https://user-images.githubusercontent.com/46803871/53933253-74658780-406b-11e9-9b22-59575078abc4.jpg)

**Comment by pvphit** [comment]
![6](https://user-images.githubusercontent.com/46803871/53933271-8a734800-406b-11e9-9b98-dbb834fee9a8.jpg)
