### ISSUE TITLE
Individual Chatting 

### ISSUE THREAD

**Issue by pvphit** [pvphit/Comp-313-Section001-Group-2#5]
A user can select the person he wants to chat with.
A user can chat with only one person at a time.
A user will select the person to check whether the message is received or not.

**Comment by haocencol** [comment]
Based on the above comment, it appears this is an epic composed of 3 user stories.  If this is the case, create an "epic" label for this issue and then create 3 issues each for the above stories and label it with a "user story" label.

Definition of an epic: a group of user stories that collectively belong to a broader feature.

**Comment by haocencol** [comment]
The user story "A user can chat with only one person at a time" is more of a constraint.  In Agile, a constraint is analogous to a non-functional requirement.

**Comment by haocencol** [comment]
#6
