### ISSUE TITLE
Select chat recipient. 

### ISSUE THREAD

**Issue by haocencol** [pvphit/Comp-313-Section001-Group-2#6]
#5 
A user can select the person he wants to chat with by typing the name in the search box.
A user can see the list of user in grid or list view

**Comment by pvphit** [comment]
![1](https://user-images.githubusercontent.com/46803871/53933771-c7d8d500-406d-11e9-8c9f-b4e60e5dd2d8.jpg)

**Comment by pvphit** [comment]
![2](https://user-images.githubusercontent.com/46803871/53933780-d3c49700-406d-11e9-98c7-bed86a8cdb6d.jpg)

**Comment by pvphit** [comment]
![3](https://user-images.githubusercontent.com/46803871/53933785-dcb56880-406d-11e9-802a-9158f332225d.jpg)

**Comment by pvphit** [comment]
![4](https://user-images.githubusercontent.com/46803871/53933794-e343e000-406d-11e9-9d0d-dc3f64dc0aff.jpg)

**Comment by pvphit** [comment]
![5](https://user-images.githubusercontent.com/46803871/53933802-f22a9280-406d-11e9-9452-3ce6503e4c14.jpg)
